### ISSUE TITLE
Expects wide terminal window

### ISSUE THREAD

**Issue by dsemaya** [MacroMan/PHPTerminalProgressBar#1]
This code expects a wide terminal window.  If your window is narrower than it expects to see something like this:

[>
[>
[=>
[==>
[===>
[====>
[=====>
[======>
[=======>
[========>
[=========>
[==========>
[===========>
[============>                                                                                        ] - 12% - 12/100^C

**Comment by MacroMan** [comment]
In theory it would be easy enough to achieve this automatically using tput, however that would stop this working on Windows. My aim with this is to keep it simple, so I won't be implementing a clever work around for that.

I have however added a property that you can set, $narrow, that will halve the bar width and will display correctly on narrow windows or native server screens.
